.TH "ps/_ps.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ps/_ps.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <_gl\&.h>\fP
.br
\fC#include <_cl\&.h>\fP
.br
\fC#include <OpenCL/cl_gl_ext\&.h>\fP
.br
\fC#include <OpenGL/CGLDevice\&.h>\fP
.br
\fC#include <OpenGL/CGLCurrent\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKERNELS_NUMBER\fP   2"
.br
.ti -1c
.RI "#define \fBFUNCTION_NUMBER\fP   1"
.br
.ti -1c
.RI "#define \fBPARAM_NUMBER\fP   7"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "t_vec3f \fBmouse\fP"
.br
.ti -1c
.RI "float \fBcam_w\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FUNCTION_NUMBER   1"

.SS "#define KERNELS_NUMBER   2"

.SS "#define PARAM_NUMBER   7"

.SH "Variable Documentation"
.PP 
.SS "float cam_w"

.PP
\fBDeprecated\fP
.RS 4
Useless/Forgiven Usage 
.RE
.PP

.SS "t_vec3f mouse"

.PP
\fBDeprecated\fP
.RS 4
Useless/Forgiven Usage 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
