.TH "demo Directory Reference" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
demo Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.main\&.c\fP"
.br
.ti -1c
.RI "file \fBfloating\&.c\fP"
.br
.ti -1c
.RI "file \fBmain_test\&.c\fP"
.br
.in -1c
