.TH "fantasy Directory Reference" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fantasy Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfantasy\&.h\fP"
.br
.ti -1c
.RI "file \fBsetoid\&.c\fP"
.br
.ti -1c
.RI "file \fBtest\&.c\fP"
.br
.in -1c
