.TH "gl Directory Reference" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gl Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcallback\&.c\fP"
.br
.ti -1c
.RI "file \fBcore\&.c\fP"
.br
.ti -1c
.RI "file \fBimage\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_hook\&.c\fP"
.br
.ti -1c
.RI "file \fBrenderer\&.c\fP"
.br
.ti -1c
.RI "file \fBshader\&.c\fP"
.br
.ti -1c
.RI "file \fButil\&.c\fP"
.br
.ti -1c
.RI "file \fBvertices\&.c\fP"
.br
.ti -1c
.RI "file \fBwindow\&.c\fP"
.br
.in -1c
