.TH "cl/compute.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl/compute.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <_gl\&.h>\fP
.br
\fC#include <_cl\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBconnect\fP (cl_device_id *device_id)"
.br
.ti -1c
.RI "cl_context \fBcreate_context\fP (cl_device_id device_id, cl_context_properties *props)"
.br
.ti -1c
.RI "cl_command_queue \fBcreate_command\fP (cl_context context, cl_device_id device_id)"
.br
.ti -1c
.RI "cl_kernel \fBcreate_kernel\fP (cl_context context, cl_device_id device_id, char *path, char *name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int connect (cl_device_id * device_id)"

.SS "cl_command_queue create_command (cl_context context, cl_device_id device_id)"

.SS "cl_context create_context (cl_device_id device_id, cl_context_properties * props)"

.SS "cl_kernel create_kernel (cl_context context, cl_device_id device_id, char * path, char * name)"

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
