.TH "gl/core.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gl/core.c
.SH SYNOPSIS
.br
.PP
\fC#include <_gl\&.h>\fP
.br
\fC#include <mlx\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBinit\fP (void)"
.br
.ti -1c
.RI "int \fBloop\fP (\fBt_mlx_context\fP *mc)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBt_mlx_context\fP \fBg_mlx_context\fP"
.br
.ti -1c
.RI "\fBt_callback\fP \fBg_callback\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBn\fP"
.br
.ti -1c
.RI "   int(* \fBf\fP )()"
.br
.ti -1c
.RI "   void * \fBp\fP"
.br
.ti -1c
.RI "} \fBevent_table\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* init (void)"
Global _gl init\&. Calls \fBt_callback\&.initearly\fP, \fBt_callback\&.initlate\fP 
.SS "int loop (\fBt_mlx_context\fP * mc)"
Global _gl loop\&. Render each user's window\&. Calls \fBt_callback\&.earlyloop\fP, \fBt_callback\&.loop\fP, \fBt_callback\&.lateloop\fP 
.SH "Variable Documentation"
.PP 
.SS "struct { \&.\&.\&. } 	 event_table[]"
\fBInitial value:\fP
.PP
.nf
= {
     { 2, NULL, NULL },
     { 3, NULL, NULL },
     { 4, NULL, NULL },
     { 5, NULL, NULL },
     { 6, NULL, NULL },
     { 12, NULL, NULL },
     { 17, NULL, NULL },
     { -1, NULL, NULL }
}
.fi
.SS "int(* f) ()"

.SS "\fBt_callback\fP g_callback"
\fBInitial value:\fP
.PP
.nf
= (t_callback){
    \&.error = error_callback,
    \&.windowpos = pos_callback,
    \&.windowsize = resize_callback,
    \&.windowclose = destroy_callback,
    \&.windowrefresh = NULL,
    \&.windowfocus = focus_test,
    \&.windowiconify = NULL,
    \&.framebuffersize = NULL,
    \&.mousebutton = mouse_button_callback,
    \&.cursorpos = cursor_pos,
    \&.cursorenter = NULL,
    \&.scroll = scroll_callback,
    \&.key = key_callback,
    \&.uchar = NULL,
    \&.charmods = NULL,
    \&.drop = NULL,
    \&.joystick = NULL,
    \&.initearly = NULL,
    \&.initlate = NULL,
    \&.earlyloop = NULL,
    \&.loop = NULL,
    \&.lateloop = NULL,
    \&.mlxwindowclose = NULL,
    \&.mlxwindowresize = NULL,
    \&.mlxmousebutton = NULL
}
.fi
Default \fBt_callback\fP value 
.SS "\fBt_mlx_context\fP g_mlx_context"
\fBInitial value:\fP
.PP
.nf
= {
    MULTIPLE,

    { 0, 0 },
    { 0, 0 },

    0,
    STAILQ_HEAD_INITIALIZER(g_mlx_context\&.w_head),
    STAILQ_HEAD_INITIALIZER(g_mlx_context\&.i_head),
    NULL
}
.fi
Default \fBt_mlx_context\fP value 
.SS "int n"

.SS "void* p"

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
