.TH "deprecated" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecatedDeprecated List 
 \- 
.IP "\fBGlobal \fBcam_w\fP \fP" 1c
Useless/Forgiven Usage  
.IP "\fBGlobal \fBcreate_window\fP (int key)\fP" 1c
Useless/Forgiven Usage  
.IP "\fBGlobal \fBdebug\fP (int key)\fP" 1c
Useless/Forgiven Usage  
.IP "\fBGlobal \fBdestroy_callback\fP (GLFWwindow *window)\fP" 1c
Useless/Forgiven Usage  
.IP "\fBGlobal \fBerror_callback\fP (int error, const char *message)\fP" 1c
Useless/Forgiven Usage  
.IP "\fBGlobal \fBerror_callback\fP (int error, const char *message)\fP" 1c
Useless/Forgiven Usage  
.IP "\fBGlobal \fBmouse\fP \fP" 1c
Useless/Forgiven Usage  
.IP "\fBGlobal \fBrender\fP (t_window *window)\fP" 1c
You must choose between rendering a renderer or a window\&.  
.IP "\fBGlobal \fBswitch_mlx_mode\fP (int key)\fP" 1c
Useless/Forgiven Usage 
.PP

