.TH "fantasy/fantasy.h" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fantasy/fantasy.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_set\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBbool\fP   int"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_set\fP \fBt_set\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define bool   int"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_set\fP \fBt_set\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
