.TH "demo/floating.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
demo/floating.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <mlx\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBf\fP (void *\fBp\fP)"
.br
.ti -1c
.RI "int \fB_loop\fP ()"
.br
.ti -1c
.RI "int \fBdrag\fP (int \fBx\fP, int \fBy\fP, void *param)"
.br
.ti -1c
.RI "int \fBpress\fP (int button, int \fBx\fP, int \fBy\fP, void *param)"
.br
.ti -1c
.RI "int \fBrelease\fP (int button, int \fBx\fP, int \fBy\fP, void *param)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBmlx\fP"
.br
.ti -1c
.RI "void * \fBwindow\fP [2]"
.br
.ti -1c
.RI "void * \fBimage\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBx\fP"
.br
.ti -1c
.RI "   int \fBy\fP"
.br
.ti -1c
.RI "   int \fBx_origin\fP"
.br
.ti -1c
.RI "   int \fBy_origin\fP"
.br
.ti -1c
.RI "} \fB_drag\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int _loop ()"

.SS "int drag (int x, int y, void * param)"

.SS "int f (void * p)"

.SS "int main ()"

.SS "int press (int button, int x, int y, void * param)"

.SS "int release (int button, int x, int y, void * param)"

.SH "Variable Documentation"
.PP 
.SS "struct { \&.\&.\&. } 	 _drag"

.SS "char* data"

.SS "void* image"

.SS "void* mlx"

.SS "void* window[2]"

.SS "int x"

.SS "int x_origin"

.SS "int y"

.SS "int y_origin"

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
