.TH "demo/main_test.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
demo/main_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <mlx\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBf\fP (void *\fBp\fP)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBmlx\fP"
.br
.ti -1c
.RI "void * \fBwindow\fP [2]"
.br
.ti -1c
.RI "void * \fBimage\fP [3]"
.br
.ti -1c
.RI "char * \fBdata\fP [3]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int f (void * p)"

.SS "int main ()"

.SH "Variable Documentation"
.PP 
.SS "char* data[3]"

.SS "void* image[3]"

.SS "void* mlx"

.SS "void* window[2]"

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
