.TH "incs/mlx.h" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
incs/mlx.h
.SH SYNOPSIS
.br
.PP
\fC#include <_gl\&.h>\fP
.br
\fC#include <sys/queue\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_size\fP"
.br
.ti -1c
.RI "struct \fBs_window_list\fP"
.br
.ti -1c
.RI "struct \fBs_image_list\fP"
.br
.ti -1c
.RI "struct \fBs_mlx_context\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmlx_init\fP   \fBinit\fP"
.br
.ti -1c
.RI "#define \fBmlx_new_window\fP   \fBnew_window\fP"
.br
.ti -1c
.RI "#define \fBmlx_clear_window\fP   \fBclear_window\fP"
.br
.ti -1c
.RI "#define \fBmlx_pixel_put\fP   \fBpixel_put\fP"
.br
.ti -1c
.RI "#define \fBmlx_get_data_addr\fP   \fBget_data_addr\fP"
.br
.ti -1c
.RI "#define \fBmlx_put_image_to_window\fP   \fBput_image_to_window\fP"
.br
.ti -1c
.RI "#define \fBmlx_loop\fP   \fBloop\fP"
.br
.ti -1c
.RI "#define \fBmlx_loop_hook\fP   \fBloop_hook\fP"
.br
.ti -1c
.RI "#define \fBmlx_mouse_hook\fP   \fBmouse_hook\fP"
.br
.ti -1c
.RI "#define \fBmlx_hook\fP   \fBhook\fP"
.br
.ti -1c
.RI "#define \fBmlx_new_image\fP   \fBnew_image\fP"
.br
.ti -1c
.RI "#define \fBX_SIZE\fP   r\->\fBwindow_size\&.x\fP"
.br
.ti -1c
.RI "#define \fBY_SIZE\fP   r\->\fBwindow_size\&.y\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_window_list\fP \fBt_window_list\fP"
.br
.ti -1c
.RI "typedef struct \fBs_image_list\fP \fBt_image\fP"
.br
.ti -1c
.RI "typedef struct \fBs_mlx_context\fP \fBt_mlx_context\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define mlx_clear_window   \fBclear_window\fP"

.SS "#define mlx_get_data_addr   \fBget_data_addr\fP"

.SS "#define mlx_hook   \fBhook\fP"

.SS "#define mlx_init   \fBinit\fP"

.SS "#define mlx_loop   \fBloop\fP"

.SS "#define mlx_loop_hook   \fBloop_hook\fP"

.SS "#define mlx_mouse_hook   \fBmouse_hook\fP"

.SS "#define mlx_new_image   \fBnew_image\fP"

.SS "#define mlx_new_window   \fBnew_window\fP"

.SS "#define mlx_pixel_put   \fBpixel_put\fP"

.SS "#define mlx_put_image_to_window   \fBput_image_to_window\fP"

.SS "#define X_SIZE   r\->\fBwindow_size\&.x\fP"

.SS "#define Y_SIZE   r\->\fBwindow_size\&.y\fP"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_image_list\fP \fBt_image\fP"

.SS "typedef struct \fBs_mlx_context\fP \fBt_mlx_context\fP"

.PP
\fBTodo\fP
.RS 4
merge mlx_context with renderer 
.RE
.PP

.SS "typedef struct \fBs_window_list\fP \fBt_window_list\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
