.TH "my_set" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_set
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBbool\fP(* \fBequals\fP )(struct \fBmy_set\fP *)"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "\fBbool\fP(* my_set::equals) (struct \fBmy_set\fP *)"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
