.TH "gl/renderer.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gl/renderer.c
.SH SYNOPSIS
.br
.PP
\fC#include <_gl\&.h>\fP
.br
\fC#include <mlx\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOLOR_LEN\fP   15"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_renderer\fP (\fBt_renderer\fP *r)"
.br
.ti -1c
.RI "void \fBassign_shader\fP (\fBt_renderer\fP *r, char *v_path, char *f_path)"
.br
.ti -1c
.RI "int \fBrender\fP (\fBt_window\fP *\fBwindow\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBcam_w\fP"
.br
.ti -1c
.RI "struct \fBs_mlx_context\fP \fBg_mlx_context\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLOR_LEN   15"

.SH "Function Documentation"
.PP 
.SS "void assign_shader (\fBt_renderer\fP * r, char * v_path, char * f_path)"
Internal tool for setting up shaders in a \fBt_renderer\fP\&. 
.SS "void init_renderer (\fBt_renderer\fP * r)"
A basic \fBt_renderer\fP init\&. 
.SS "int render (\fBt_window\fP * window)"
The basic render function\&. 
.PP
\fBDeprecated\fP
.RS 4
You must choose between rendering a renderer or a window\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "float cam_w"

.PP
\fBDeprecated\fP
.RS 4
Useless/Forgiven Usage 
.RE
.PP

.SS "struct \fBs_mlx_context\fP g_mlx_context"
Default \fBt_mlx_context\fP value 
.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
