.TH "s_callback" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_callback
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_gl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "GLFWerrorfun \fBerror\fP"
.br
.ti -1c
.RI "GLFWwindowposfun \fBwindowpos\fP"
.br
.ti -1c
.RI "GLFWwindowsizefun \fBwindowsize\fP"
.br
.ti -1c
.RI "GLFWwindowclosefun \fBwindowclose\fP"
.br
.ti -1c
.RI "GLFWwindowrefreshfun \fBwindowrefresh\fP"
.br
.ti -1c
.RI "GLFWwindowfocusfun \fBwindowfocus\fP"
.br
.ti -1c
.RI "GLFWwindowiconifyfun \fBwindowiconify\fP"
.br
.ti -1c
.RI "GLFWframebuffersizefun \fBframebuffersize\fP"
.br
.ti -1c
.RI "GLFWmousebuttonfun \fBmousebutton\fP"
.br
.ti -1c
.RI "GLFWcursorposfun \fBcursorpos\fP"
.br
.ti -1c
.RI "GLFWcursorenterfun \fBcursorenter\fP"
.br
.ti -1c
.RI "GLFWscrollfun \fBscroll\fP"
.br
.ti -1c
.RI "GLFWkeyfun \fBkey\fP"
.br
.ti -1c
.RI "GLFWcharfun \fBuchar\fP"
.br
.ti -1c
.RI "GLFWcharmodsfun \fBcharmods\fP"
.br
.ti -1c
.RI "GLFWdropfun \fBdrop\fP"
.br
.ti -1c
.RI "GLFWjoystickfun \fBjoystick\fP"
.br
.ti -1c
.RI "\fBMLXinitearlyfun\fP \fBinitearly\fP"
.br
.ti -1c
.RI "\fBMLXinitlatefun\fP \fBinitlate\fP"
.br
.ti -1c
.RI "\fBMLXloopearlyfun\fP \fBearlyloop\fP"
.br
.ti -1c
.RI "\fBMLXloopfun\fP \fBloop\fP"
.br
.ti -1c
.RI "\fBMLXlooplatefun\fP \fBlateloop\fP"
.br
.ti -1c
.RI "\fBMLXwindowclosefun\fP \fBmlxwindowclose\fP"
.br
.ti -1c
.RI "\fBMLXwindowresize\fP \fBmlxwindowresize\fP"
.br
.ti -1c
.RI "\fBMLXmousefun\fP \fBmlxmousebutton\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "GLFWcharmodsfun s_callback::charmods"

.SS "GLFWcursorenterfun s_callback::cursorenter"

.SS "GLFWcursorposfun s_callback::cursorpos"

.SS "GLFWdropfun s_callback::drop"

.SS "\fBMLXloopearlyfun\fP s_callback::earlyloop"

.SS "GLFWerrorfun s_callback::error"

.SS "GLFWframebuffersizefun s_callback::framebuffersize"

.SS "\fBMLXinitearlyfun\fP s_callback::initearly"

.SS "\fBMLXinitlatefun\fP s_callback::initlate"

.SS "GLFWjoystickfun s_callback::joystick"

.SS "GLFWkeyfun s_callback::key"

.SS "\fBMLXlooplatefun\fP s_callback::lateloop"

.SS "\fBMLXloopfun\fP s_callback::loop"

.SS "\fBMLXmousefun\fP s_callback::mlxmousebutton"

.SS "\fBMLXwindowclosefun\fP s_callback::mlxwindowclose"

.SS "\fBMLXwindowresize\fP s_callback::mlxwindowresize"

.SS "GLFWmousebuttonfun s_callback::mousebutton"

.SS "GLFWscrollfun s_callback::scroll"

.SS "GLFWcharfun s_callback::uchar"

.SS "GLFWwindowclosefun s_callback::windowclose"

.SS "GLFWwindowfocusfun s_callback::windowfocus"

.SS "GLFWwindowiconifyfun s_callback::windowiconify"

.SS "GLFWwindowposfun s_callback::windowpos"

.SS "GLFWwindowrefreshfun s_callback::windowrefresh"

.SS "GLFWwindowsizefun s_callback::windowsize"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
