.TH "s_context" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_context
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_cl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "cl_device_id \fBdevice_id\fP"
.br
.ti -1c
.RI "cl_context \fBcontext\fP"
.br
.ti -1c
.RI "cl_command_queue \fBcommands\fP"
.br
.ti -1c
.RI "char ** \fBkernel_names\fP"
.br
.ti -1c
.RI "char ** \fBfunction_names\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "cl_command_queue s_context::commands"

.SS "cl_context s_context::context"

.SS "cl_device_id s_context::device_id"

.SS "char** s_context::function_names"

.SS "char** s_context::kernel_names"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
