.TH "s_fps" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_fps
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_gl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstr\fP [32]"
.br
.ti -1c
.RI "double \fBframes\fP"
.br
.ti -1c
.RI "double \fBt\fP"
.br
.ti -1c
.RI "double \fBt1\fP"
.br
.ti -1c
.RI "double \fBt2\fP"
.br
.ti -1c
.RI "float \fBdt\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float s_fps::dt"

.SS "double s_fps::frames"

.SS "char s_fps::str[32]"

.SS "double s_fps::t"

.SS "double s_fps::t1"

.SS "double s_fps::t2"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
