.TH "s_image_list" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_image_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mlx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTAILQ_ENTRY\fP (\fBs_image_list\fP) next"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBs_size\fP \fBsize\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "s_image_list::STAILQ_ENTRY (\fBs_image_list\fP)"

.SH "Field Documentation"
.PP 
.SS "char* s_image_list::data"

.SS "struct \fBs_size\fP s_image_list::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
