.TH "s_kernel" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_kernel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_cl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t * \fBGlobalWorkSize\fP"
.br
.ti -1c
.RI "unsigned int \fBk_size\fP"
.br
.ti -1c
.RI "cl_kernel * \fBkernels\fP"
.br
.ti -1c
.RI "unsigned int \fBp_size\fP"
.br
.ti -1c
.RI "cl_mem * \fBparams\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t* s_kernel::GlobalWorkSize"

.SS "unsigned int s_kernel::k_size"

.SS "cl_kernel* s_kernel::kernels"

.SS "unsigned int s_kernel::p_size"

.SS "cl_mem* s_kernel::params"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
