.TH "s_mlx_context" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_mlx_context
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mlx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTAILQ_HEAD\fP (window_head, \fBs_window_list\fP) w_head"
.br
.ti -1c
.RI "\fBSTAILQ_HEAD\fP (image_head, \fBs_image_list\fP) i_head"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBmode\fP"
.br
.ti -1c
.RI "struct \fBs_size\fP \fBscreen_size\fP"
.br
.ti -1c
.RI "struct \fBs_size\fP \fBvidmode_size\fP"
.br
.ti -1c
.RI "unsigned int \fBwindow_nbr\fP"
.br
.ti -1c
.RI "\fBt_window\fP * \fBactive_window\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "s_mlx_context::STAILQ_HEAD (window_head, \fBs_window_list\fP)"

.SS "s_mlx_context::STAILQ_HEAD (image_head, \fBs_image_list\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBt_window\fP* s_mlx_context::active_window"

.SS "unsigned int s_mlx_context::mode"

.SS "struct \fBs_size\fP s_mlx_context::screen_size"

.SS "struct \fBs_size\fP s_mlx_context::vidmode_size"

.SS "unsigned int s_mlx_context::window_nbr"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
