.TH "s_param" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_param
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_cl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBcreate_function\fP"
.br
.ti -1c
.RI "unsigned int \fBcl_mem_mask\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "void * \fBwhatever\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int s_param::cl_mem_mask"

.SS "unsigned int s_param::create_function"

.SS "size_t s_param::size"

.SS "void* s_param::whatever"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
