.TH "s_renderer" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_renderer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_gl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBmode\fP"
.br
.ti -1c
.RI "unsigned int \fBVAO\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned int \fBvertex_shader\fP"
.br
.ti -1c
.RI "   unsigned int \fBfragment_shader\fP"
.br
.ti -1c
.RI "   unsigned int \fBprogram\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned int \fBVBOP\fP"
.br
.ti -1c
.RI "   unsigned int \fBVBOC\fP"
.br
.ti -1c
.RI "   unsigned int \fBVBOT\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned int \fBvertices_nbr\fP"
.br
.ti -1c
.RI "   t_vec3f * \fBv_pos\fP"
.br
.ti -1c
.RI "   t_vec3f * \fBv_col\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBvpos_location\fP"
.br
.ti -1c
.RI "   int \fBvcol_location\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   t_vec2i \fBwindow_size\fP"
.br
.ti -1c
.RI "   t_vec3f * \fBv_tex\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned int \fBvtex_location\fP"
.br
.ti -1c
.RI "   unsigned int \fBtexture\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "struct { \&.\&.\&. } "

.SS "struct { \&.\&.\&. } "

.SS "struct { \&.\&.\&. } "

.SS "struct { \&.\&.\&. } "

.SS "struct { \&.\&.\&. } "

.SS "unsigned int s_renderer::fragment_shader"

.SS "unsigned int s_renderer::mode"

.SS "unsigned int s_renderer::program"

.SS "unsigned int s_renderer::texture"

.SS "t_vec3f* s_renderer::v_col"

.SS "t_vec3f* s_renderer::v_pos"

.SS "t_vec3f* s_renderer::v_tex"

.SS "unsigned int s_renderer::VAO"

.SS "unsigned int s_renderer::VBOC"

.SS "unsigned int s_renderer::VBOP"

.SS "unsigned int s_renderer::VBOT"

.SS "int s_renderer::vcol_location"

.SS "unsigned int s_renderer::vertex_shader"

.SS "unsigned int s_renderer::vertices_nbr"

.SS "int s_renderer::vpos_location"

.SS "unsigned int s_renderer::vtex_location"

.SS "t_vec2i s_renderer::window_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
