.TH "s_set" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_set
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fantasy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbool\fP(* \fBequals\fP )(\fBt_set\fP *)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBbool\fP(* s_set::equals) (\fBt_set\fP *)"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
