.TH "s_size" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_size
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mlx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int s_size::height"

.SS "int s_size::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
