.TH "s_window" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_window
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_gl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "GLFWwindow * \fBw\fP"
.br
.ti -1c
.RI "struct \fBs_renderer\fP \fBr\fP"
.br
.ti -1c
.RI "t_vec2i \fBsize\fP"
.br
.ti -1c
.RI "t_vec2i \fBposition\fP"
.br
.ti -1c
.RI "unsigned int \fBflush\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int s_window::flush"

.SS "t_vec2i s_window::position"

.SS "struct \fBs_renderer\fP s_window::r"

.SS "t_vec2i s_window::size"

.SS "GLFWwindow* s_window::w"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
