.TH "s_window_list" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_window_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mlx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTAILQ_ENTRY\fP (\fBs_window_list\fP) next"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_window\fP \fBw\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "s_window_list::STAILQ_ENTRY (\fBs_window_list\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBt_window\fP s_window_list::w"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
