.TH "test" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtata\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBx\fP"
.br
.ti -1c
.RI "   int \fBy\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct \fBtest::tata\fP \fBt\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "int test::i"

.SS "struct \fBtest::tata\fP  test::t"

.SS "int test::x"

.SS "int test::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
