.TH "todo" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBGlobal \fBapply_callback\fP (t_window *window, t_callback *callback)\fP" 1c
Find out a better way to achieve that  
.IP "\fBGlobal \fBclear_window\fP (t_mlx_context *mlx_context, t_window *window)\fP" 1c
Need to be reworked Clears a \fBt_window\fP  
.IP "\fBGlobal \fBfocus_test\fP (GLFWwindow *window, int action)\fP" 1c
Should trigger a userland MLX focus callback  
.IP "\fBGlobal \fBg_callback\fP \fP" 1c
This ressource should not be required  
.IP "\fBGlobal \fBg_mlx_context\fP \fP" 1c
This ressource should not be required  
.IP "\fBGlobal \fBloop_hook\fP (t_mlx_context *mlx_context, int(*f)(), void *param)\fP" 1c
Handle param  
.IP "\fBGlobal \fBmouse_button_callback\fP (GLFWwindow *window, int button, int action, int mods)\fP" 1c
Should trigger a userland MLX mouse button callback  
.IP "\fBGlobal \fBmouse_hook\fP (t_window *window, int(*f)(), void *param)\fP" 1c
Handle param  
.IP "\fBGlobal \fBpixel_put\fP (t_mlx_context *mlx_context, t_window *window, int x, int y, int color)\fP" 1c
Need to be reworked Put a pixel into a \fBt_window\fP in respect to MLX's  
.IP "\fBGlobal \fBresize_callback\fP (GLFWwindow *window, int width, int height)\fP" 1c
Should trigger a userland MLX resize callback  
.IP "\fBGlobal \fBscroll_callback\fP (GLFWwindow *window, double xoffset, double yoffset)\fP" 1c
Should trigger a userland MLX scroll callback  
.IP "\fBGlobal \fBt_mlx_context\fP \fP" 1c
merge mlx_context with renderer  
.IP "\fBGlobal \fBVIDMODE\fP \fP" 1c
This ressource should not be required  
.IP "\fBGlobal \fBvidmodes\fP \fP" 1c
This ressource should not be required 
.PP

