.TH "gl/util.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gl/util.c
.SH SYNOPSIS
.br
.PP
\fC#include <_gl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBversion\fP (void)"
.br
.ti -1c
.RI "void \fBinit_fps\fP (\fBt_fps\fP *fps)"
.br
.ti -1c
.RI "void \fBrun_fps\fP (\fBt_window\fP *\fBwindow\fP, \fBt_fps\fP *fps)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_fps (\fBt_fps\fP * fps)"
Init a \fBt_fps\fP\&. 
.SS "void run_fps (\fBt_window\fP * window, \fBt_fps\fP * fps)"
Update a \fBt_fps\fP\&. 
.SS "void version (void)"
Version 
.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
