.TH "gl/vertices.c" 3 "Thu Oct 12 2017" "Version 0.0.1" "_gl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gl/vertices.c
.SH SYNOPSIS
.br
.PP
\fC#include <_gl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "t_vec4f * \fBnew_vertices\fP (unsigned int size)"
.br
.ti -1c
.RI "void \fBline\fP (t_vec4f *v_pos, unsigned int size, unsigned int grain)"
.br
.ti -1c
.RI "void \fBcube\fP (t_vec4f *v_pos, unsigned int size, unsigned int grain)"
.br
.ti -1c
.RI "void \fBlarge_cube\fP (t_vec4f *v_pos, unsigned int size, unsigned int grain)"
.br
.ti -1c
.RI "void \fBcircle\fP (t_vec4f *v_pos, unsigned int size, unsigned int grain)"
.br
.ti -1c
.RI "void \fBinf_cone\fP (t_vec4f *v_pos, unsigned int size, unsigned int grain)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void circle (t_vec4f * v_pos, unsigned int size, unsigned int grain)"

.SS "void cube (t_vec4f * v_pos, unsigned int size, unsigned int grain)"

.SS "void inf_cone (t_vec4f * v_pos, unsigned int size, unsigned int grain)"

.SS "void large_cube (t_vec4f * v_pos, unsigned int size, unsigned int grain)"

.SS "void line (t_vec4f * v_pos, unsigned int size, unsigned int grain)"

.SS "t_vec4f* new_vertices (unsigned int size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for _gl from the source code\&.
